# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devnews < Formula
  desc "TUI engineering blog aggregator"
  homepage "https://github.com/matheuskafuri/devnews"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.1.0/devnews_0.1.0_darwin_amd64.tar.gz"
      sha256 "648ec5d9497c94fceab47ac8d241047974a87bbc1a1e16ab9e16841dd77db5b5"

      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.1.0/devnews_0.1.0_darwin_arm64.tar.gz"
      sha256 "582edfcec2370a4f6be05f65fa7900922734ceb03d1a9b206e5394ef9960d5df"

      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.1.0/devnews_0.1.0_linux_amd64.tar.gz"
      sha256 "6d1903a427436d1bf8f0fc428627df2e1dbec4989b826ea9bb555ecb36a6e6d7"
      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.1.0/devnews_0.1.0_linux_arm64.tar.gz"
      sha256 "2063bf28d1dd28525f487a6bb47bafcc21ff1f2dbd984ecb8bfa17041d20c4b2"
      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  test do
    system "#{bin}/devnews", "version"
  end
end
